# Generated by Django 2.0.9 on 2018-11-30 03:12

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('councilmatic_core', '0002_auto_20181129_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChicagoBill',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('councilmatic_core.bill',),
        ),
        migrations.CreateModel(
            name='ChicagoEvent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('councilmatic_core.event',),
        ),
    ]
