# Generated by Django 2.0.9 on 2018-11-17 05:37

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legislative', '0005_auto_20171005_2028'),
        ('councilmatic_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChicagoBill',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('legislative.bill',),
        ),
        migrations.CreateModel(
            name='ChicagoEvent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('councilmatic_core.event',),
        ),
    ]
