# Generated by Django 3.2.16 on 2023-01-09 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicago', '0004_chicagopersonstatistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='chicagopersonstatistic',
            name='legislation_success_rate',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
