# Generated by Django 3.2.25 on 2024-11-22 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chicago', '0005_chicagopersonstatistic_legislation_success_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchBill',
            fields=[
                ('text', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='chicago.chicagobill')),
            ],
        ),
    ]
