# Generated by Django 3.2.25 on 2024-12-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicago', '0006_searchbill'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchbill',
            name='extras',
            field=models.JSONField(null=True),
        ),
    ]
