name: Associate commits to heroku release in sentry

on:
  deployment_status

jobs:
  associate:
    if: github.event.deployment_status.state == 'success' && github.event.deployment.environment == 'chi-councilmatic-production'
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v3
        with:
          ref: "${{ github.event.deployment_status.deployment.ref }}"
          fetch-depth: 0
      - name: install sentry-cli
        run: pip install sentry-cli
      - name: Sleep to make sure that heroku deployment is really done
        run: sleep 120
        shell: bash
      - name: get release version
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: echo "HEROKU_RELEASE=`heroku config:get HEROKU_RELEASE_VERSION -a chi-councilmatic-production`-chi-councilmatic-production"  >> "$GITHUB_ENV"
      - name: inform sentry about release
        env:
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: |
          sentry-cli releases new -p chicago-councilmatic $HEROKU_RELEASE
          sentry-cli releases set-commits $HEROKU_RELEASE
          sentry-cli releases finalize $HEROKU_RELEASE
        
