name: Associate commits to heroku release in sentry

on:
  deployment_status

jobs:
  associate:
    if: github.event.deployment_status.state == 'success' && github.event.deployment.environment == chi-councilmatic-production
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: "${{ github.event.deployment_status.deployment.ref }}"
          fetch-depth: 0
      - name: install sentry-cli
        run: pip install sentry-cli
      - name: create release
        env:
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          COMMIT: "${{ github.event.deployment_status.deployment.ref }}" 
        run: |
          sentry-cli releases new -p chicago-councilmatic $COMMIT
          sentry-cli releases set-commits $COMMIT
          sentry-cli releases finalize $COMMIT
      - name: set HEROKU_SLUG_COMMIT
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          COMMIT: "${{ github.event.deployment_status.deployment.ref }}" 
        run: heroku config:set HEROKU_SLUG_COMMIT=$COMMIT -a chi-councilmatic-production`
        
