name: Associate commits to heroku release in sentry

on:
  workflow_dispatch

jobs:
  associate:
    runs-on: ubuntu-latest

    steps:
      - name: get release name
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku config:get HEROKU_RELEASE_VERSION -a chi-councilmatic-production
